params:
  random_seed: 42
is_python: True

exec_path: <p>
conda_env: <p>


logging:
  gdrive_storage_folder: "https://drive.google.com/drive/folders/1bCKbgY29CXsgYSwBHk49weolkA5cBePT?usp=share_link"
  use_wandb: False
  use_tb: False
